=== alexgoussev/maja_gitlab/Plugins/Common/Interfaces/Schemas/PSC-SL-411-0032-CG_Schemas/JobProcessingInformations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:include schemaLocation="dico/misc/misc.xsd"/>
	<xs:element name="JobProcessingInformations">
		<xs:annotation>
			<xs:documentation>fichier d'information sur l'ex√©cution MACCS</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MNT_Statistics">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Min" type="A_LENGTH_VALUE"/>
							<xs:element name="Max" type="A_LENGTH_VALUE"/>
							<xs:element name="Average" type="A_LENGTH_VALUE"/>
							<xs:element name="Standard_Deviation" type="A_LENGTH_VALUE"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Processing_Flags_And_Modes_List">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Processing_Flags_And_Modes" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Key" type="xs:string"/>
										<xs:element name="Value" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alexgoussev/maja_gitlab/Plugins/SENTINEL2_MUSCATE/Interfaces/Config/Templates/L2.product/JPI_ALL.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobProcessingInformations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JobProcessingInformations.xsd">
	<MNT_Statistics>
		<Min unit="m">NOT_INITIALIZED -9</Min>
		<Max unit="m">NOT_INITIALIZED 2901</Max>
		<Average unit="m">NOT_INITIALIZED 761.3285042</Average>
		<Standard_Deviation unit="m">NOT_INITIALIZED 641.3953638</Standard_Deviation>
	</MNT_Statistics>
	<Processing_Flags_And_Modes_List>
		<Processing_Flags_And_Modes>
			<Key>Processing_Mode</Key>
			<Value>NOT_INITIALIZED INIT_MODE</Value>
		</Processing_Flags_And_Modes>
		<Processing_Flags_And_Modes>
			<Key>Adjacency_Effects_And_Slope_Correction</Key>
			<Value>NOT_INITIALIZED true</Value>
		</Processing_Flags_And_Modes>	
		<Processing_Flags_And_Modes>
			<Key>Quality_check</Key>
			<Value>false</Value>		
		</Processing_Flags_And_Modes>
		<Processing_Flags_And_Modes>
			<Key>Validity_Flag</Key>
			<Value>NOTV</Value>
		</Processing_Flags_And_Modes>
		<Processing_Flags_And_Modes>
			<Key>Cirrus_Correction</Key>
			<Value>NOT_INITIALIZED true</Value>
		</Processing_Flags_And_Modes>
		<Processing_Flags_And_Modes>
			<Key>CAMS_Processing</Key>
			<Value>NOT_INITIALIZED Desactivateddd</Value>		
		</Processing_Flags_And_Modes>
	</Processing_Flags_And_Modes_List>
</JobProcessingInformations>
